name: Auto Key

on:
  schedule:
    - cron: "*/1 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate five encoded keys
        run: |
          echo '{ "keys": [] }' > keys.json
          for i in 1 2 3 4 5
          do
            RAW="Free_phonghub$RANDOM$RANDOM"
            ENC=$(echo -n "$RAW" | base64)
            jq --arg k "$ENC" '.keys += [$k]' keys.json > temp.json
            mv temp.json keys.json
          done

      - name: Commit
        run: |
          git config user.name "Auto Key Bot"
          git config user.email "bot@github"
          git add keys.json
          git commit -m "Update keys"
          git push
